# Generated by Django 4.2.4 on 2023-08-10 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_quizresult_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Quiz.category'),
        ),
    ]
